### ISSUE TITLE
Bad indentation and work distribution

### ISSUE THREAD

**Issue by GrosQuildu** [brunoproduit/roca#1]
Hi
I had tried to use your code and noticed three things:
* indentation is wrong in roca.py and optimization.py scripts:
    ```python
          a_prime = start
          while a_prime < stop:
            if manager.finished:
              break 
              
              # Construct polynomial
              m_inv = int(inverse_mod(M_prime, N))
    ```
    Infinite loop over `if manager.finished`.

* Distribution of work (below `# Spawn processes`) is wrong. For example with 512 bit key and 7 cpus:
   ```
    top = 0xc5772
    c_prime = 0x65ab4
    ord_prime = 0x125430
    start | stop |  stop-start
    0x80000 | 0x1c359 | -0x63ca7
    0x1c359 | 0x386b2 | 0x1c359
    0x386b2 | 0x54a0c | 0x1c35a
    0x54a0c | 0x70d65 | 0x1c359
    0x70d65 | 0x8d0bf | 0x1c35a
    0x8d0bf | 0xa9418 | 0x1c359
    0xa9418 | 0xc5772 | 0x1c35a
    ```
    First worker returns immediately, and next four do unnecessary jobs.
    
    Should be something like:
    ```
    top = 0xc5772
    c_prime = 0x65ab4
    ord_prime = 0x125430
    start | stop |  stop-start
    0x80000 | 0x89ec8 | 0x9ec8
    0x89ec8 | 0x93d90 | 0x9ec8
    0x93d90 | 0x9dc58 | 0x9ec8
    0x9dc58 | 0xa7b20 | 0x9ec8
    0xa7b20 | 0xb19e8 | 0x9ec8
    0xb19e8 | 0xbb8b0 | 0x9ec8
    0xbb8b0 | 0xc5778 | 0x9ec8
    ```

* manager.finished not working, when one worker finds the factorization, other workers don't stop

**Comment by brunoproduit** [comment]
Hey, thanks for bringing that up !
Indeed the code seems to be wrongly indented and the workers are broken.
